### ISSUE TITLE
MapboxNavigationNative umbrella header omits several headers

### ISSUE THREAD

**Issue by IodaMikeMapbox** [mapbox/mapbox-navigation-ios#2394]
`MapboxNavigationNative` v9 doesn't include headers: 'MBHistoryPlayer.h', 'MBGetRouteCallback.h', 'MBSetRouteCallback.h', 'MapboxNavigationNativeHistoryPlayer.h', 'MBGetTraceAttributesCallback.h', 'MBUpdateSensorDataCallback.h', 'MBConfigureRouterCallback.h', 'MBLocateCallback.h', 'MBIterationResult.h', 'MBGetStatusCallback.h', 'MBUpdateLocationCallback.h', 'MBChangeRouteLegCallback.h', 'MBPushHistoryCallback.h'.
Our CI tests fail because of the generated warnings about that, this is a potential problem for subsequent core work, and it blocks any prerelease.

@mapbox/navnative

**Comment by 1ec5** [comment]
```
    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBHistoryPlayer.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetRouteCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBSetRouteCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MapboxNavigationNativeHistoryPlayer.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetTraceAttributesCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBUpdateSensorDataCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBConfigureRouterCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBLocateCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBIterationResult.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetStatusCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBUpdateLocationCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBChangeRouteLegCallback.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBPushHistoryCallback.h'
```

**Comment by vmihaylenko** [comment]
I guess we fixed this in further releases

**Comment by vmihaylenko** [comment]
> https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-ios/960/workflows/6d3cad76-bd95-470b-99d5-715bf38a8293/jobs/15604/steps
> 
> ```
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBHistoryPlayer.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetRouteCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBSetRouteCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MapboxNavigationNativeHistoryPlayer.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetTraceAttributesCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBUpdateSensorDataCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBConfigureRouterCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBLocateCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBIterationResult.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBGetStatusCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBUpdateLocationCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBChangeRouteLegCallback.h'
> 
>     - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBPushHistoryCallback.h'
> ```

this one contains types from a PR which wasn't even merged

**Comment by 1ec5** [comment]
As of MapboxNavigationNative v9.2.1 and mapbox/mapbox-navigation-ios#2412, the umbrella header still lacks three header includes:

```
    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBXFeature.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBXGeometry.h'

    - WARN  | xcodebuild:  <module-includes>:1:1: warning: umbrella header for module 'MapboxNavigationNative' does not include header 'MBXExpected.h'
```

**Comment by 1ec5** [comment]
These three include statements are still missing from the umbrella header in MapboxNavigationNative v14.1.1.

**Comment by 1ec5** [comment]
Likely fixed in MapboxNavigationNative v14.1.2.

**Comment by 1ec5** [comment]
Fixed in MapboxNavigationNative v14._x_.
