### ISSUE TITLE
Dual-use lane incorrectly highlighted when taking off ramp

### ISSUE THREAD

**Issue by avi-c** [mapbox/mapbox-navigation-ios#2879]
Found an instance where we choose the wrong lane highlighting visuals for a given maneuver

If you set a route that begins at the "Apple" location preset in the simulator and sets a destination that will generate a route that takes the exit from I-280 N to CA-85 N then you will see the error. One such destination coordinate is: 37.344831, -122.055065

![Simulator Screen Shot - iPhone 11 - 2021-03-22 at 14 20 12](https://user-images.githubusercontent.com/10037825/112061888-5e28a800-8b1c-11eb-8e6d-45ac8715a9c4.png)

The lane indication should show the lane second from the right as having a slight-right indicated, not the straight.

**Comment by avi-c** [comment]
I believe the issue is in the logic here: https://github.com/mapbox/mapbox-navigation-ios/blob/f82bb539ae95ab04673be10a68408181218d896b/Sources/MapboxNavigation/LaneView.swift#L43

This particular maneuver has a primary direction of "right", but the lane is a straight/slight-right combo and the "straight" portion is incorrectly preferred.

This should ultimately be fixed with changes from the Directions API where it can specifically and unambiguously indicate the active direction of an active lane.

For now we can look at altering the matching logic to try and catch this case.

**Comment by 1ec5** [comment]
Indeed, [the way in question](https://www.openstreetmap.org/way/875173184) is tagged `turn:lanes=none|none|none|through;slight_right|slight_right`, which means the number 4 lane would have `straight` and `slight_right` indications. This earlier case would’ve done the right thing:

https://github.com/mapbox/mapbox-navigation-ios/blob/f82bb539ae95ab04673be10a68408181218d896b/Sources/MapboxNavigation/LaneView.swift#L28-L29

The maneuver direction for an `off ramp` instruction is always `left` or `right`, never `slight_right`, because you’d never say the ramp is “to the slight right” side of the road. But as far as turn lanes are concerned, taking an off ramp is usually a slight turn. So we could add a special case around here to make `off ramp` instructions slighter:

https://github.com/mapbox/mapbox-navigation-ios/blob/f82bb539ae95ab04673be10a68408181218d896b/Sources/MapboxNavigation/LanesView.swift#L85-L87

That said, #2801 would give the existing code access to less ambiguous directional information from the router, so there are diminishing returns for adding edge cases around maneuver types.

**Comment by jill-cardamon** [comment]
I'm not seeing the same maneuvers displayed here on the release-v2.0 branch:

![Simulator Screen Shot - iPhone 8 - 2021-04-07 at 10 12 58](https://user-images.githubusercontent.com/43434254/113881055-121b6b80-978a-11eb-91ef-5dad0d036505.png)

With #2801, the highlighting is now correct, and the number 4 lane still shows as a `straight, right`. Adding the extra cases would be a nice addition to the UI.

![Simulator Screen Shot - iPhone 8 - 2021-04-07 at 10 52 54](https://user-images.githubusercontent.com/43434254/113902028-7693f600-979d-11eb-8bc5-ade87f0a1ff2.png)

**Comment by jill-cardamon** [comment]
Fixed in #2942 (screenshots included).
